language: node_js
node_js:
  - 14
  - 16
env:
  - JWT_KEY='YOUR_JWT_KEY' GOOGLE_STORAGE_BUCKET_NAME='your_google_storage_bucket_name'
  - JWT_KEY='YOUR_JWT_KEY' GOOGLE_STORAGE_BUCKET_NAME='your_google_storage_bucket_name'

