apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: project-id
build:
  artifacts:
    #Local configuration
    - image: org/project/servicename
      context: service-folder #folder where codebase is stored
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: org/project/servicename2
      context: service2-folder
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {} #this  tag policy uses the tag latest of image
  #Local configuration
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s-dev/*
deploy:
  kubectl: {}
