apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets
data:
  JWT_KEY: <base64-base64-value>
  GOOGLE_PROJECT_ID: <base64-value>
  GOOGLE_STORAGE_BUCKET_NAME: <base64-value>
  GOOGLE_CLIENT_ID: <base64-value>
  GOOGLE_CLIENT_SECRET: <base64-value>
  SENDGRID_API_KEY: <base64-value>
  SENDGRID_SENDER_EMAIL: <base64-value>
  TWILIO_ACCOUNT_SID: <base64-value>
  TWILIO_AUTH_TOKEN: <base64-value>
  TWILIO_PHONE_NUMBER: <base64-value>

  #JWT_KEY cmd:  echo -n 'your_jwt_key' | base64
  #GOOGLE_PROJECT_ID cmd:  echo -n 'your_project_id' | base64
  #GOOGLE_STORAGE_BUCKET_NAME cmd:  echo -n 'your_google_storage_bucket_name' | base64
  #GOOGLE_CLIENT_ID cmd:  echo -n 'your_google_client_id' | base64
  #GOOGLE_CLIENT_SECRET cmd:  echo -n 'your_google_client_secret' | base64
  #SENDGRID_API_KEY cmd:  echo -n 'your_sendgrid_api_key' | base64
  #SENDGRID_SENDER_EMAIL cmd:  echo -n 'your_sendgrid_sender_email' | base64

  #kubectl create secret generic jwt-secret --from-literal=JWT_KEY=YOUR_SUPERSECRET

  #Don't forget to create the google-application-credentials secret with in the folder where the JSON is
  #kubectl create secret generic google-application-credentials --from-file=google-application-credentials.json=./google-application-credentials.json
